Clean up tutorial organization
nextstrain/docs.nextstrain.org pull request #48
Opened 2021-02-24 01:00 UTC by huddlej

Consolidates introductory tutorials (Zika and TB) into this repository, removes references to the alternate Zika tutorial from the Augur repository, and provides more explanatory titles for each tutorial.

2021-02-26 20:04 UTC, eharkins approved these changes
Thanks John! I activated a RTD build for this here https://docs.nextstrain.org/en/dedupe-zika-docs/tutorials/index.html just to check it builded and looked as I expected from the diff - looks good, that build version can be deactivated (or maybe that happens automatically if you delete the branch after merging).

Just a reminder that https://github.com/nextstrain/augur/blob/master/docs/tutorials/tb_tutorial.md should be removed when you merge. 

Meanwhile I suppose you can wait to remove https://github.com/nextstrain/augur/blob/master/docs/tutorials/zika_tutorial.md from augur until it is transformed into a snakemake oriented advanced tutorial / guide.

2021-02-26 20:31 UTC, eharkins requested changes
I think a redirect might be necessary for zika otherwise the merged (replacing latest for the branch name) version of this link might 404: https://docs.nextstrain.org/en/dedupe-zika-docs/tutorials/zika_tutorial.html (this 404s now and I believe that behavior will carry over when merged to master/latest).

Seems like we want to redirect https://docs.nextstrain.org/en/latest/tutorials/zika_tutorial.html to 
https://docs.nextstrain.org/en/latest/tutorials/zika.html - even though in the future the zika_tutorial will become something else altogether (snakemake tutorial), i think this is the best place we can redirect it for now in the absence of that snakemake tutorial.

Which I think can be implemented by configuring the following redirect at https://readthedocs.org/dashboard/nextstrain/redirects/:
```
Page Redirect
/tutorials/zika_tutorial.html -> https://docs.nextstrain.org/en/latest/tutorials/zika.html
```

2021-02-26 21:27 UTC, huddlej commented
Thank you for checking this out, @eharkins! I added a redirect for `/tutorials/zika_tutorial.html -> /tutorials/zika.html` and it works as expected for https://docs.nextstrain.org/en/dedupe-zika-docs/tutorials/zika_tutorial.html.

I will follow this PR up with the separate one for the Zika + Snakemake tutorial we discussed (starting with the old `zika_tutorial.md` content initially).

2021-03-01 18:04 UTC, huddlej commented
Merging this since the Zika tutorial in Augur no longer exists and new branches from current `master` break on the fetch_docs command when they try to pull that Zika tutorial. I created a new branch and [a draft PR for refining this Snakemake-based Zika tutorial and the TB tutorial](https://github.com/nextstrain/docs.nextstrain.org/pull/50).

2021-03-01 18:04 UTC, merged